In [2]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [5]:
list_

['1', '2', '3', '4', '5']

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [7]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

List_ is just a list whereas thr array_list is a numpy array.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [11]:
[type(i) for i in list_]

[str, str, str, str, str]

In [12]:
[type(i) for i in array_list]

[numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_]

Q3. Considering the following changes in the variable, array_list:

In [14]:
array_list = np.array(object = list_, dtype = int)

In [15]:
array_list

array([1, 2, 3, 4, 5])

In [16]:
[type(i) for i in array_list]

[numpy.int64, numpy.int64, numpy.int64, numpy.int64, numpy.int64]

In [17]:
[type(i) for i in list_]

[str, str, str, str, str]

The data types of array_list element has now changed to integer wheras the data types for elements in list_ variable remains string.

In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
num_array.shape

(2, 3)

In [22]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [28]:
arr = np.zeros((3,3))

In [29]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Create an identity matrix of shape (5,5) using numpy functions?

In [31]:
arr1 = np.eye(5,5)

In [32]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])